build:
  image: node:5.11.1
  commands:
  - echo "build commands"
  - npm install

publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: aroach@gmail.com
    repo: ciscodevnet/imapex-drone-nodejs
    tag: latest
    file: Dockerfile
    insecure: false